### ISSUE TITLE
Support for variables in filter

### ISSUE THREAD

**Issue by doomsower** [apollographql/graphql-anywhere#38] opened 2017-02-08 20:31 UTC
Imagine that we have a query
```graphql
const regionDetails = gql`
  query regionDetails($_id: ID!, $language:String, $withBounds: Boolean!, $withPOIs: Boolean!) {
    region(_id: $_id, language: $language) {
      ...RegionCore
      ...RegionPOIs @include(if: $withPOIs)
      ...RegionBounds @include(if: $withBounds)
    }
  }
  ${Fragments.Core}
  ${Fragments.POIs}
  ${Fragments.Bounds}
`;
```

And then we want to filter some data against this query:

```js
const {region} = filter(regionDetails, data);
```

Currently this will throw error, because underlying graphql call does not receive variables, which are required to process directives.

I think for such cases `filter` function needs third argument, variables.

**Comment by helfer** [comment] 2017-02-09 01:17
@doomsower Yes, I think you're right. It's contributor week right now, so if you have time to work on  a PR, I can help you get it merged very quickly! 🙂

**Comment by stubailo** [comment] 2017-02-09 01:20
I would say another simple solution would be to include all fields - since if the variable didn't match the field wouldn't be there in the first place. So we shouldn't add a variable option but instead somehow treat all fields as included.

**Comment by doomsower** [comment] 2017-02-09 08:25
To do this, I can add one more option, say `ignoreIncludeDirectives`, into `ExecOptions`and then in pass it into `ExecContext`. Then during execution I can ignore calls to `shouldInclude`. There are no more ways (besides directives) variables can affect shape of the result, right? So I'd prefer this to passing variables to filter function. If this is ok, I can submit PR.

**Comment by doomsower** [comment] 2017-02-09 09:21
While working this I stumbled upon another related question:

```js
    const queryWithDirectives = gql`
      query withDirectives($withAvatar: Boolean!) {
        alias: name
        height(unit: METERS)
        avatar @include(if: $withAvatar) {
          square
        }
      }
    `;

    check(queryWithDirectives, { alias: 'Bob', height: 1.89 });
```

Does it check or not? I think in this case variables are required to make correct answer.

**Comment by helfer** [comment] 2017-02-10 02:17
@doomsower I think you should check in the source code to find out how checking currently works.

**Comment by doomsower** [comment] 2017-02-10 09:07
@helfer I looked into `check` code, I can see what it does, but I have no idea what would someone expect to get if he uses check with query with directives. It is used in `propType`, but prop types are for fragments, I think. So I won't touch it.
Meanwhile, I submitted PR for `filter`.

**Comment by cvle** [comment] 2017-08-15 14:53
We've been waiting for this for a long time, anyway we can help?

**Comment by stubailo** [comment] 2017-12-05 22:16
Hi, in the release of Apollo Client 2.0, we moved this package into the `apollo-client` repo, if the issue is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere

**Closed by stubailo** 2017-12-05 22:16 UTC
