### ISSUE TITLE
Problems with fragments and filter

### ISSUE THREAD

**Issue by beagleknight** [apollographql/graphql-anywhere#29] opened 2017-01-09 10:31 UTC
Hi there!

I found a problem related to fragments and filter function. I'm not sure if it's a bug or I'm doing something wrong.

I have these fragments:

```
fragment CommentThread on Comment {
  author {
    name
  }
  replies {
    id
  }
  ...Comment
}

fragment Comment on Comment {
  replies {
    ...CommentData
  }
  ...CommentData
}

fragment CommentData on Comment {
  id
  body
  author {
    name
    avatarUrl
  }
}
```

My component structure is the following:

```
CommentThread
  Comment
    Comment
    ...
```

That means a `Comment` can have replies that are also a comment.

The query is working well and it returns the expected result. The problem is when I filter the data for `CommentThreadComponent` I'm losing the `replies` extra fields and just getting the `id`.
I thought it was because the `filter` function is not parsing the query correctly so it's not overriding the `replies` field as described in `Comment` fragment.

On the other hand, the `author` field is working as expected so the `filter` function is working well and passing the whole data to the children components.

Any thoughts?

**Comment by tmeasday** [comment] 2017-01-09 22:09
Hi @beagleknight.

Looking at the `CommentThread` I see `replies { id }` but no other `replies` fields. So I wouldn't expect any other fields to get filtered. Is it possible you inteded to include the `...Comment` fragment in `CommentThread`?

**Comment by stubailo** [comment] 2017-01-09 22:34
By the way, GraphQL doesn't support recursion so even doing that will only get  2 levels of comment nesting.

**Comment by beagleknight** [comment] 2017-01-10 08:16
@tmeasday you are totally right! I edited the issue description. I copied it by hand so I made a mistake 😞 . Now I'm asking for a few more fields for `replies`. The query is working well but the filter not.
@stubailo I'm aware of it, thanks!. In our project we are using three nested levels as a workaround so the user cannot reply a third-level comment.

**Comment by helfer** [comment] 2017-01-10 13:00
@beagleknight This looks a whole lot like #28, where the issue is with how the result gets merged.

**Comment by stubailo** [comment] 2017-12-05 22:15
Hi, in the release of Apollo Client 2.0, we moved this into the `apollo-client` repo, if it is still relevant please reopen there! https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere

**Closed by stubailo** 2017-12-05 22:15 UTC
